"""initial schema

Revision ID: 1928aa1edfa2
Revises:
Create Date: 2026-04-26 16:56:43.869468

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1928aa1edfa2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.String(length=128), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("baseline_region", sa.String(length=100), nullable=True),
        sa.Column("consent_granted", sa.Boolean(), nullable=False),
        sa.Column("consent_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "account_id"),
        sa.UniqueConstraint("tenant_id", "phone_number"),
    )
    op.create_index("idx_accounts_phone", "accounts", ["tenant_id", "phone_number"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(
        "idx_api_keys_hash",
        "api_keys",
        ["key_hash"],
        unique=False,
        postgresql_where="is_active = TRUE",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.String(length=128), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("transaction_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("recommended_action", sa.String(length=10), nullable=False),
        sa.Column("mode_triggered", sa.Integer(), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signal_drivers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fast_path", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(length=20), nullable=True),
        sa.CheckConstraint("recommended_action IN ('ALLOW','STEP-UP','HOLD')"),
        sa.CheckConstraint("mode_triggered IN (1,2,3)"),
        sa.CheckConstraint("risk_score BETWEEN 0 AND 100"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sessions_phone", "sessions", ["tenant_id", "phone_number"], unique=False)
    op.create_index(
        "idx_sessions_tenant_created", "sessions", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("consent_status", sa.String(length=20), nullable=False),
        sa.Column("authorised_by", sa.String(length=50), nullable=False),
        sa.Column("authorised_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location_retrieved", sa.Boolean(), nullable=False),
        sa.Column("raw_consent_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("incident_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("incident_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("visit_locations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("home_zone", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("maps_url", sa.Text(), nullable=True),
        sa.Column("evidence_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incidents")
    op.drop_table("consent_records")
    op.drop_index("idx_sessions_tenant_created", table_name="sessions")
    op.drop_index("idx_sessions_phone", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("idx_api_keys_hash", table_name="api_keys", postgresql_where="is_active = TRUE")
    op.drop_table("api_keys")
    op.drop_index("idx_accounts_phone", table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("tenants")
    # ### end Alembic commands ###
