name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy-frontend:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Deploy to Vercel
        run: npx vercel@latest --token ${{ secrets.VERCEL_TOKEN }} --prod --yes --cwd ./frontend
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
